light:
  - platform: lvgl
    name: "Dining One"
    id: dining_1_light
    widget: dining_1_led_indicator
    default_transition_length: 0ms

switch:
  - platform: lvgl
    id: dining_1_switch
    name: "Dining 1 switch"
    widget: dining_led_1_switch_widget

lvgl:
  pages:
    - id: dining_1_page
      widgets:
        - obj:
            id: background_4
            x: 0
            y: 0
            width: 360
            height: 360
            bg_color: 0x000000
            border_width: 0
            pad_all: 0
        
        - switch:
            id: dining_led_1_switch_widget
            width: 150
            height: 80
            align: center
            on_value:
              then:
              - if:
                  condition:
                    - lambda: 'return x == 1;'
                  then:
                    - light.turn_on: dining_1_light
                    - lambda: 'ESP_LOGI("INFO","Dining one ON");'
                  else:
                    - light.turn_off: dining_1_light
                    - lambda: 'ESP_LOGI("INFO","Dining one OFF");'

        - led:
            id: dining_1_led_indicator
            width: 50
            height: 50
            x: -130
            y: -156
            align: bottom_mid
            color: 0x00FF00
        
        - label:
            id: dining_1_brightness_label
            align_to:
              id: dining_1_led_indicator
              align: bottom_mid
            x: 50
            y: -20
            text: "--%"
            text_font: roboto_32
            text_color: 0xFFFFFF

        - label:
            id: dining_1_page_label
            align: top_mid
            y: 40
            text: "Dining 1"
            text_font: roboto_32
            text_color: 0xFFFFFF
    
      on_swipe_left:
        - lambda: 'id(current_page) = 3;'
        - lvgl.page.show:
            id: living_3_page
            animation: OUT_LEFT
      on_swipe_right:
        - lambda: 'id(current_page) = 5;'
        - lvgl.page.show:  
            id: dining_2_page
            animation: OUT_RIGHT